Create TABLE code_space (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    author_uuid UUID NULL REFERENCES "user"(uuid) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    language VARCHAR(150) NOT NULL,
    contents TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE (name)
);

Create TABLE code_space_access (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_uuid UUID NOT NULL REFERENCES "user"(uuid) ON DELETE CASCADE,
    code_space_id INT NOT NULL REFERENCES code_space(id) ON DELETE CASCADE,
    level INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE (user_uuid, code_space_id)
);
